<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 */
namespace eftec\examples\example1\repo;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class AddresRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li><b>address_id</b>: int (alias of column address_id) </li>
 * <li><b>address</b>: string (alias of column address) </li>
 * <li><b>address2</b>: string (alias of column address2) </li>
 * <li><b>district</b>: string (alias of column district) </li>
 * <li><b>city_id</b>: int (alias of column city_id) </li>
 * <li><b>postal_code</b>: string (alias of column postal_code) </li>
 * <li><b>phone</b>: string (alias of column phone) </li>
 * <li><b>last_update</b>: datetime (alias of column last_update) </li>
 * <li><b>_city_id</b>: MANYTOONE (alias of column _city_id) (CityRepoModel)</li>
 * <li><b>_customer</b>: ONETOMANY (alias of column _customer) (CustomerRepoModel)</li>
 * <li><b>_staff</b>: ONETOMANY (alias of column _staff) (StaffRepoModel)</li>
 * <li><b>_store</b>: ONETOMANY (alias of column _store) (StoreRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 1.4 Date generated Tue, 12 Dec 2023 19:40:10 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * @see CityRepoModel
 * @see CustomerRepoModel
 * @see StaffRepoModel
 * @see StoreRepoModel
 */
class AddresRepo extends AbstractAddresRepo
{
    public static $ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
