<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 */
namespace eftec\examples\example1\repo;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class FilmRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li><b>film_id</b>: int (alias of column film_id) </li>
 * <li><b>title</b>: string (alias of column title) </li>
 * <li><b>description</b>: binary (alias of column description) </li>
 * <li><b>release_year</b>: string (alias of column release_year) </li>
 * <li><b>language_id</b>: int (alias of column language_id) </li>
 * <li><b>original_language_id</b>: int (alias of column original_language_id) </li>
 * <li><b>rental_duration</b>: int (alias of column rental_duration) </li>
 * <li><b>rental_rate</b>: float (alias of column rental_rate) </li>
 * <li><b>length</b>: int (alias of column length) </li>
 * <li><b>replacement_cost</b>: float (alias of column replacement_cost) </li>
 * <li><b>rating</b>: string (alias of column rating) </li>
 * <li><b>special_features</b>: string (alias of column special_features) </li>
 * <li><b>last_update</b>: datetime (alias of column last_update) </li>
 * </ul>
 * Generated by PdoOne Version 1.4 Date generated Tue, 12 Dec 2023 19:40:10 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>

 */
class FilmRepo extends AbstractFilmRepo
{
    public static $ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
