<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 */
namespace eftec\examples\example1\repo;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class StoreRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li><b>store_id</b>: int (alias of column store_id) </li>
 * <li><b>manager_staff_id</b>: int (alias of column manager_staff_id) </li>
 * <li><b>address_id</b>: int (alias of column address_id) </li>
 * <li><b>last_update</b>: datetime (alias of column last_update) </li>
 * <li><b>_address_id</b>: MANYTOONE (alias of column _address_id) (AddresRepoModel)</li>
 * <li><b>_manager_staff_id</b>: MANYTOONE (alias of column _manager_staff_id) (StaffRepoModel)</li>
 * <li><b>_customer</b>: ONETOMANY (alias of column _customer) (CustomerRepoModel)</li>
 * <li><b>_inventory</b>: ONETOMANY (alias of column _inventory) (InventoryRepoModel)</li>
 * <li><b>_staff</b>: ONETOMANY (alias of column _staff) (StaffRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 1.00 Date generated Sat, 11 Mar 2023 14:32:14 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * @see AddresRepoModel
 * @see StaffRepoModel
 * @see CustomerRepoModel
 * @see InventoryRepoModel
 * @see StaffRepoModel
 */
class StoreRepo extends AbstractStoreRepo
{
    const ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
