<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 */
namespace eftec\tests\sakila2021;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class CountryRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li><b>country_id</b>: int (alias of column country_id) </li>
 * <li><b>country</b>: string (alias of column country) </li>
 * <li><b>last_update</b>: datetime (alias of column last_update) </li>
 * <li><b>_city</b>: ONETOMANY (alias of column _city) (CityRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 1.4 Date generated Tue, 12 Dec 2023 19:40:55 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * @see CityRepoModel
 */
class CountryRepo extends AbstractCountryRepo
{
    public static $ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
