<?php
/** @noinspection AccessModifierPresentedInspection
 * @noinspection PhpUnusedAliasInspection
 * @noinspection UnknownInspectionInspection
 * @noinspection PhpUnused
 */
namespace eftec\examples\example2\repo;

use Exception;
// [EDIT:use] you can edit this part
// Here you can add your custom use
// [/EDIT] end of edit

/**
 * Class ActorRepo Copyright (c) Jorge Castro C. (https://github.com/EFTEC/PdoOne)<br>
 * <ul>
 * <li><b>actor_id</b>: int (alias of column actor_id) </li>
 * <li><b>first_name</b>: string (alias of column first_name) </li>
 * <li><b>last_name</b>: string (alias of column last_name) </li>
 * <li><b>last_update</b>: datetime (alias of column last_update) </li>
 * <li><b>_film_actor</b>: ONETOMANY (alias of column _film_actor) (FilmActorRepoModel)</li>
 * </ul>
 * Generated by PdoOne Version 1.00 Date generated Sat, 11 Mar 2023 18:09:05 -0300.<br>
 * <b>YOU CAN EDIT THIS CODE</b>. It is not replaced by the generation of the code, unless it is indicated<br>
 * @see FilmActorRepoModel
 */
class ActorRepo extends AbstractActorRepo
{
    const ME=__CLASS__;
    
    // [EDIT:content] you can edit this part
    // Here you can add your custom content.
    // [/EDIT] end of edit
}
