<?php // eftec/CliOne(1.28) PHP configuration file (date gen: 2023-09-02 07:34). DO NOT EDIT THIS FILE 
/**
 * It is a configuration file
 */
$config=[
    'databaseType' => 'mysql',
    'server' => '127.0.0.1',
    'user' => 'root',
    'pwd' => 'abc.123',
    'database' => 'sakila',
    'logFile' => false,
    'charset' => NULL,
    'nodeId' => 1,
    'tableKV' => '',
];
